import { loadEnvFile } from 'node:process'; import pg from 'pg';
loadEnvFile('.env'); const pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:String(process.env.DATABASE_SSL).toLowerCase()==='false'?false:{rejectUnauthorized:false}}); const c=await pool.connect();
try { await c.query('begin read only'); const q=(s)=>c.query(s).then(r=>r.rows);
const result={
 paidProvenance:await q(`select coalesce(gateway_status,'NULL') gateway_status, count(*)::int total, count(*) filter(where gateway_transaction_id is null)::int without_transaction, count(*) filter(where gateway_payload is null)::int without_payload from "run-payments" where status='paid' group by gateway_status order by total desc`),
 orphanEvents:await q(`select event_type, count(*)::int total, min(received_at) first_at, max(received_at) last_at from "run-payment-events" pe left join "run-payments" p on p.id=pe.payment_id where p.id is null group by event_type order by event_type`),
 registrationWithoutPayment:await q(`select r.id,r.status,r.created_at,r.updated_at,r.amount_cents,r.payload->>'fullName' full_name from "run-registrations" r left join "run-payments" p on p.registration_id=r.id where p.id is null order by r.created_at`),
 duplicateSummary:await q(`select count(*)::int duplicate_cpf_groups, sum(total-1)::int extra_records, count(*) filter(where paid_count>1)::int groups_multiple_paid, sum(greatest(paid_count-1,0))::int extra_paid from (select cpf_hash,count(*) total,count(*) filter(where status='paid') paid_count from "run-registrations" group by cpf_hash having count(*)>1)x`),
 duplicateStatusPatterns:await q(`select statuses,count(*)::int groups from (select cpf_hash,string_agg(status,',' order by created_at) statuses from "run-registrations" group by cpf_hash having count(*)>1)x group by statuses order by groups desc`),
 email:await q(`select count(*) filter(where confirmation_email_sent_at is null)::int missing, count(*) filter(where confirmation_email_error is not null)::int errors, count(*) filter(where confirmation_email_id is null)::int missing_provider_id from "run-registrations" where status='paid'`),
 emailActions:await q(`select action,count(*)::int total,count(distinct entity_id)::int registrations from "run-audit-logs" where action like 'email.confirmation.%' group by action order by action`),
 webhookTypes:await q(`select event_type,count(*)::int total,count(distinct payment_id)::int payments from "run-payment-events" group by event_type order by event_type`),
 paidConfirmationChannels:await q(`select case when exists(select 1 from "run-payment-events" pe where pe.payment_id=p.id and pe.event_type='infinitepay.payment_status_changed') then 'infinitepay_webhook' when exists(select 1 from "run-payment-events" pe where pe.payment_id=p.id and pe.event_type like 'manual.%') then 'manual_event_only' else 'no_confirmation_event' end channel,count(*)::int total from "run-payments" p where p.status='paid' group by 1 order by 1`),
 paidEventMultiplicity:await q(`select count(*) filter(where webhook_count=0)::int no_webhook,count(*) filter(where webhook_count=1)::int one_webhook,count(*) filter(where webhook_count>1)::int repeated_webhook,max(webhook_count)::int max_webhooks from (select p.id,count(pe.id) filter(where pe.event_type='infinitepay.payment_status_changed') webhook_count from "run-payments" p left join "run-payment-events" pe on pe.payment_id=p.id where p.status='paid' group by p.id)x`),
 paymentEventTiming:await q(`select count(*)::int paid, round(avg(extract(epoch from (p.paid_at::timestamptz-r.created_at::timestamptz)))::numeric,2) avg_creation_to_paid_seconds, round(max(extract(epoch from (p.paid_at::timestamptz-r.created_at::timestamptz)))::numeric,2) max_creation_to_paid_seconds from "run-payments" p join "run-registrations" r on r.id=p.registration_id where p.status='paid'`),
 daily:await q(`select to_char(paid_at::timestamptz at time zone 'America/Manaus','YYYY-MM-DD') as paid_day,count(*)::int paid,sum(amount_cents)::int revenue_cents from "run-registrations" where status='paid' group by 1 order by 1`),
 shirt:await q(`select payload->>'shirtSize' size,count(*)::int athletes from "run-registrations" where status='paid' group by 1 order by 1`),
 ids:await q(`select count(*)::int total,count(distinct id)::int distinct_ids from "run-registrations" union all select count(*)::int,count(distinct id)::int from "run-payments"`)
}; console.log(JSON.stringify(result,null,2)); await c.query('rollback'); } finally {c.release();await pool.end();}
