export const eventInfo = {
  name: 'FunPace Run 2026',
  edition: 'Season 01',
  city: 'Porto Velho',
  state: 'RO',
  contactEmail: 'funpacerunclub@gmail.com',
  instagramUrl: 'https://www.instagram.com/fun__pace/',
  dateLabel: '19 de Setembro, 2026',
  startTimeLabel: '06:00',
  startsAt: '2026-09-19T06:00:00-04:00',
  locationName: 'Complexo Madeira Mamoré',
  locationLabel: 'Complexo Madeira Mamoré - RO',
  distances: ['10 Km', '5 Km'],
  distanceOptions: [
    { value: '10K', label: '10 Km' },
    { value: '5K', label: '5 Km' },
  ],
  genderOptions: [
    { value: 'female', label: 'Feminino' },
    { value: 'male', label: 'Masculino' },
    { value: 'non_binary', label: 'Não binario' },
    { value: 'prefer_not_to_answer', label: 'Prefiro não informar' },
  ],
  currentLot: 'Lote 1',
  currentLotPriceCents: 7999,
  currentLotCapacity: 100,
  offerNote: 'Inscrição confirmada somente após pagamento aprovado.',
  kitItems: [
    'Camiseta',
    'Número de peito',
    'Medalha',
    '+ Surpresas',
  ],
  shirtSizes: ['P', 'M', 'G', 'GG'],
};
